language: java
install:
- mvn install -DskipTests=true
before_script:
- mysql -e 'DROP DATABASE IF EXISTS is429;'
- mysql < database.sql
- cd ..
- wget https://commondatastorage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.1.zip
- unzip appengine-java-sdk-1.9.1.zip
- rm appengine-java-sdk-1.9.1.zip
script:
- cd smu-is429-rockpaperscissorslizardspock
- mvn test
after_success:
- echo $GAE_TOKEN > ../token.txt
- "../appengine-java-sdk-1.9.1/bin/appcfg.sh --oauth2 update target/rockpaperscissorlizardspock-war-1.0-SNAPSHOT < ../token.txt"
env:
  global:
  - secure: blSaFbr8VCodykqK3UkmDkEewNPpR+iuj2DOXTstB5FOjrJ7skNggRP2CtTAo6S+xiC/bvXTGPcy0732pCpzFnTp6ch6Xjvif/N2dBbQs2u1pvpSAbI8HVi/eTGa5lAkN4MfTaWLdBzPw3+hnbMgAfHTPADLaLtRZr+fUt60b14=
