language: java
before_script:
- cd ..
- wget https://commondatastorage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.1.zip
- unzip appengine-java-sdk-1.9.1.zip
- rm appengine-java-sdk-1.9.1.zip
install:
- cd smu-is429-rockpaperscissorslizardspock
- mvn install -DskipTests=true
script:
- mvn test