language: java
install:
- mvn install -DskipTests=true
before_script:
- mysql -e 'DROP DATABASE IF EXISTS is429;'
- mysql < database.sql
- cd ..
- wget https://commondatastorage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.1.zip
- unzip appengine-java-sdk-1.9.1.zip
- rm appengine-java-sdk-1.9.1.zip
script:
- cd smu-is429-rockpaperscissorslizardspock 
- mvn test
after_success:
- appengine-java-sdk-1.9.1/bin/appcfg.sh --oauth2 update smu-is429-rockpaperscissorslizardspock/target