language: java
install:
- mvn install -DskipTests=true
before_script:
- mysql -e 'DROP DATABASE IF EXISTS is429;'
- mysql < database.sql
- cd ..
- wget https://commondatastorage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.1.zip
- unzip appengine-java-sdk-1.9.1.zip
- rm appengine-java-sdk-1.9.1.zip
script:
- cd smu-is429-rockpaperscissorslizardspock
- mvn test
after_success:
- echo $EMAIL > ../access.txt
- echo $PASSWORD >> ../access.txt
- "../appengine-java-sdk-1.9.1/bin/appcfg.sh --passin update target/rockpaperscissorlizardspock-war-1.0-SNAPSHOT
  < ../access.txt"
env:
  global:
  - secure: OHUFL4cJ3KZx39hZZ/MQcZFU/OsbIjvC4DP4wCg+NwctNQXKMLGAR8K+A10B7QmjrKsMpEOX2+7qsJScgYCkY/VOPEt4//1DzT/OKzhat8XFfudseWUAWG8DOQRg+IRcaUwoqFC0I02XsEwfii0KU4hKkOZ73MZ+eYLipQS9vJM=
  - secure: DkdzXMoUd4H1GmKWEkA+ntNQQbZY080l36N72aUJaJArp6ynzbFqShw1zIdh46TRhJ8JNJpln2eM1Ax5XdrPFPRaWVtaVbDUR9KOz9SKVT9jjN8RXSrYFZWvG33eIZNy9WsGelkIbqKffNoMI486UdD2vhT/PRjn4ZJm6y3qku4=
